[Variables]
; Line
LineCount=30
LineGap=8
LineWidth=12
LineHeight=80
LineCap=Round
; Flat, Round, Square, Triangle


; Gradient (From Color1 to Color2)
; Type in RGBA format please, 4 values separated with a comma. TY :)
Color1=255,204,0,100
Color2=170,255,0,255


; Max audio level to reach Color2 (>0.4 ideal)
VolMax=0.5


; Audio
Sensitivity=45
FFTSize=4096
FFTAttack=200
FFTDecay=100
FreqMin=20
FreqMax=16000
